### ISSUE TITLE
test on  VOC dataset (coco2voc)

### ISSUE THREAD

**Issue by ry-jojo** [danganea/iMTFA#1]
Hi, thanks for sharing the codes.
Could you please share this file "VOCOutput/annotations/val_converted.json" for voc testing?
I am facing with the errors like below when testing with --set-voc-test:

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOCOutput/annotations/val_converted.json'

Thanks in advance!

**Comment by danganea** [comment]
You're completely right! I apologise about this and thank you for your interest!

The data is here:

https://1drv.ms/u/s!Ako0GB-Fly5dgfcp-sBbUO-NE1k9cA?e=xcTCnw

Furthermore, to use it you might need to edit the `builtin.py` file which registers the VOC dataset via a `register_coco_instances` call. Editing that should be trivial.

I plan to do a commit to make it easier to use sometime this week.

**Comment by ry-jojo** [comment]
> You're completely right! I apologise about this and thank you for your interest!
> 
> The data is here:
> 
> https://1drv.ms/u/s!Ako0GB-Fly5dgfcp-sBbUO-NE1k9cA?e=xcTCnw
> 
> Furthermore, to use it you might need to edit the `builtin.py` file which registers the VOC dataset via a `register_coco_instances` call. Editing that should be trivial.
> 
> I plan to do a commit to make it easier to use sometime this week.

Many thanks for your reply!
